# observability-stack/prometheus.yml
global:
  scrape_interval: 15s # Standard-Intervall für das Scrapen
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus" # Job, um Prometheus selbst zu scrapen
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "otel-collector" # Job, um Metriken vom OpenTelemetry Collector zu scrapen
    static_configs:
      - targets: ["otel-collector:8889"] # Der Port, auf dem der Collector Prometheus-Metriken bereitstellt

  # Weitere Jobs für Services, die direkt von Prometheus gescraped werden sollen (z.B. Spring Boot Actuator)
  - job_name: "service-java-todo"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["service-java-todo:8080"]

  # Beispiel: Wenn der Go-Service direkt einen Prometheus-Endpunkt bereitstellen würde
  # - job_name: 'service-go-healthcheck'
  #   static_configs:
  #     - targets: ['service-go-healthcheck:8003']
