{{- if .Values.frontendAngular.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sretodo-chart.fullname" . }}-frontend-angular
  labels:
    {{- include "sretodo-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-angular
spec:
  replicas: {{ .Values.frontendAngular.replicaCount }}
  selector:
    matchLabels:
      {{- include "sretodo-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend-angular
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sretodo-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend-angular
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sretodo-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-frontend-angular
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontendAngular.image.repository }}:{{ .Values.frontendAngular.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontendAngular.service.port }} # Interner Nginx Port
              protocol: TCP
          # Keine OTel Env Vars nötig, da Konfig im Frontend-Code ist
          # (Ggf. anpassen, falls Collector nicht exposed wird)
          # Liveness/Readiness Probes (einfacher Check auf den Nginx Port)
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 