{{- if .Values.nginxGateway.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sretodo-chart.fullname" . }}-nginx-gateway
  labels:
    {{- include "sretodo-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-gateway
spec:
  replicas: {{ .Values.nginxGateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "sretodo-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx-gateway
  template:
    metadata:
      annotations:
        rollme: "{{ randAlphaNum 12 }}" # Force update mit längerer Zeichenkette
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "sretodo-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: nginx-gateway
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sretodo-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx-gateway
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginxGateway.image.repository }}:{{ .Values.nginxGateway.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginxGateway.service.targetPort }} # Interner Nginx Port
              protocol: TCP
          # ConfigMap für die Nginx-Konfiguration wird benötigt
          # Wir mounten die default.conf aus einer ConfigMap
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          # Liveness/Readiness Probes
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            # Der Name der ConfigMap wird hier referenziert
            name: {{ include "sretodo-chart.fullname" . }}-nginx-gateway-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 