{{- if .Values.serviceGoHealthcheck.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sretodo-chart.fullname" . }}-go-healthcheck
  labels:
    {{- include "sretodo-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: go-healthcheck
spec:
  replicas: {{ .Values.serviceGoHealthcheck.replicaCount }}
  selector:
    matchLabels:
      {{- include "sretodo-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: go-healthcheck
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sretodo-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: go-healthcheck
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sretodo-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-go-healthcheck
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.serviceGoHealthcheck.image.repository }}:{{ .Values.serviceGoHealthcheck.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.serviceGoHealthcheck.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.serviceGoHealthcheck.service.port }}"
            - name: OTEL_SERVICE_NAME
              value: "service-go-healthcheck"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.config.otel.collectorEndpointHttp }}
            # Service Discovery für die zu prüfenden Services:
            - name: CHECK_URL_STATISTIK
              value: "http://{{ include "sretodo-chart.fullname" . }}-dotnet-statistik:{{ .Values.serviceDotnetStatistik.service.port }}/health"
            - name: CHECK_URL_TODO
              value: "http://{{ include "sretodo-chart.fullname" . }}-java-todo:{{ .Values.serviceJavaTodo.service.port }}/actuator/health"
            - name: CHECK_URL_POMODORO
              value: "http://{{ include "sretodo-chart.fullname" . }}-python-pomodoro:{{ .Values.servicePythonPomodoro.service.port }}/health"
          # Liveness/Readiness Probes (Annahme: /health Endpunkt existiert auch hier)
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 