{{- if .Values.serviceJavaTodo.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sretodo-chart.fullname" . }}-java-todo
  labels:
    {{- include "sretodo-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  type: {{ .Values.serviceJavaTodo.service.type }}
  ports:
    - port: {{ .Values.serviceJavaTodo.service.port }}
      targetPort: http # Name des Ports im Deployment
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
{{- end }}
 