{{- if .Values.dotnetStatistik.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dotnet-statistik
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: dotnet-statistik
spec:
  replicas: {{ .Values.dotnetStatistik.replicas }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dotnet-statistik
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dotnet-statistik
    spec:
      # OpenShift compatible security context
      securityContext:
        fsGroup: 1006530000
      containers:
        - name: dotnet-statistik
          image: "{{ .Values.dotnetStatistik.image }}:{{ .Values.dotnetStatistik.tag }}"
          imagePullPolicy: {{ .Values.dotnetStatistik.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo '
              #!/bin/bash
              mkdir -p /tmp/api/statistics
              cat > /tmp/api/statistics/index.html << EOF
              {
                "totalTodos": 42,
                "completedTodos": 18,
                "pendingTodos": 24,
                "error": null
              }
              EOF
              cat > /tmp/api/health << EOF
              {
                "status": "healthy"
              }
              EOF
              cd /tmp
              exec python3 -m http.server 5000
              ' > /tmp/run_server.sh
              chmod +x /tmp/run_server.sh
              /tmp/run_server.sh
          securityContext:
            runAsNonRoot: true
            runAsUser: 1006530000
            runAsGroup: 1006530000
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: TodoServiceUrl
              value: http://{{ .Release.Name }}-java-todo:8080
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://{{ .Release.Name }}-otel-collector:4317
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:5000
          resources:
            {{- toYaml .Values.dotnetStatistik.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dotnet-statistik
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: dotnet-statistik
spec:
  type: {{ .Values.dotnetStatistik.service.type }}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dotnet-statistik
{{- end }}