apiVersion: apps/v1
kind: Deployment
metadata:
  name: sretodo-frontend
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.sretodoFrontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      # OpenShift compatible security context
      securityContext: {}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.sretodoFrontend.image.repository }}:{{ .Values.sretodoFrontend.image.tag | default "stable-alpine" }}"
          imagePullPolicy: {{ .Values.sretodoFrontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Add health checks
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sretodo-frontend
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.sretodoFrontend.service.type }}
  ports:
    - port: {{ .Values.sretodoFrontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend