apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-nginx-conf
  labels:
    app: sretodo
    component: frontend
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        root /usr/share/nginx/html;
        index index.html index.htm;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Optionale Sicherheitsheader oder andere Konfigurationen können hier hinzugefügt werden

        # Fehlerseiten (optional)
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    } 