apiVersion: apps/v1
kind: Deployment
metadata:
  name: sretodo-frontend
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.sretodoFrontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.sretodoFrontend.image.repository }}:{{ .Values.sretodoFrontend.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.sretodoFrontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sretodo-frontend
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.sretodoFrontend.service.type }}
  ports:
    - port: {{ .Values.sretodoFrontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend