{{- if .Values.javaTodo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-todo
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  replicas: {{ .Values.javaTodo.replicas }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: java-todo
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: java-todo
    spec:
      # OpenShift compatible security context
      securityContext:
        fsGroup: 1000
      containers:
        - name: java-todo
          image: "{{ .Values.javaTodo.image }}:{{ .Values.javaTodo.tag }}"
          imagePullPolicy: {{ .Values.javaTodo.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Add health checks
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.env.POSTGRES_DB }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.env.POSTGRES_USER }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://{{ .Release.Name }}-otel-collector:4317
          resources:
            {{- toYaml .Values.javaTodo.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-todo
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  type: {{ .Values.javaTodo.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
{{- end }}