{{- if .Values.sretodoJavaTodo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sretodo-java-todo
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  replicas: {{ .Values.sretodoJavaTodo.replicaCount }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: java-todo
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: java-todo
    spec:
      # OpenShift compatible security context
      securityContext: {}
      containers:
        - name: {{ .Chart.Name }}-java-todo
          image: "{{ .Values.sretodoJavaTodo.image.repository }}:{{ .Values.sretodoJavaTodo.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.sretodoJavaTodo.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Add health checks
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://sretodo-postgres:5432/sretodo
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sretodo-postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sretodo-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://sretodo-otel-collector:4317
---
apiVersion: v1
kind: Service
metadata:
  name: sretodo-java-todo
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  type: {{ .Values.sretodoJavaTodo.service.type }}
  ports:
    - port: {{ .Values.sretodoJavaTodo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
{{- end }}