{{- if .Values.javaTodo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-todo
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  replicas: {{ .Values.javaTodo.replicas }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: java-todo
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: java-todo
    spec:
      # Reference the global image pull secret only if defined
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      # OpenShift compatible security context
      securityContext:
        fsGroup: 1006530000
      containers:
        - name: java-todo
          image: "{{ .Values.global.repositoryPrefix }}/{{ .Values.javaTodo.imageName }}:{{ .Values.javaTodo.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Release.Name }}-postgres:5432/sretodo
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgres.env.POSTGRES_USER }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgres.env.POSTGRES_PASSWORD }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://{{ .Release.Name }}-otel-collector:4317
          securityContext:
            runAsNonRoot: true
            runAsUser: 1006530000
            runAsGroup: 1006530000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Health checks
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.javaTodo.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-todo
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
spec:
  type: {{ .Values.javaTodo.service.type }}
  ports:
    - port: {{ .Values.javaTodo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: java-todo
{{- end }}