apiVersion: apps/v1
kind: Deployment
metadata:
  name: sretodo-postgres
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: {{ .Chart.Name }}-postgres
          image: "{{ .Values.sretodoPostgres.image.repository }}:{{ .Values.sretodoPostgres.image.tag | default "14-alpine" }}"
          imagePullPolicy: {{ .Values.sretodoPostgres.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sretodo-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sretodo-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.sretodoPostgres.env.POSTGRES_DB }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-data
          {{- if .Values.sretodoPostgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: sretodo-postgres-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
---
{{- if .Values.sretodoPostgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sretodo-postgres-pvc
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sretodoPostgres.persistence.size }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: sretodo-postgres
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sretodoPostgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres