{{- if .Values.pythonPomodoro.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-python-pomodoro
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-pomodoro
spec:
  replicas: {{ .Values.pythonPomodoro.replicas }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: python-pomodoro
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: python-pomodoro
    spec:
      # Reference the global image pull secret only if defined
      {{- if .Values.global.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      {{- end }}
      # OpenShift compatible security context
      securityContext:
        fsGroup: 1006530000
      containers:
        - name: python-pomodoro
          image: "{{ .Values.global.repositoryPrefix }}/{{ .Values.pythonPomodoro.imageName }}:{{ .Values.pythonPomodoro.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: TODO_SERVICE_HOST
              value: {{ .Release.Name }}-java-todo
            - name: TODO_SERVICE_PORT
              value: "{{ .Values.javaTodo.service.port | default 8080 }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://{{ .Release.Name }}-otel-collector:4317
          securityContext:
            runAsNonRoot: true
            runAsUser: 1006530000
            runAsGroup: 1006530000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 8002
              protocol: TCP
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.pythonPomodoro.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-python-pomodoro
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: python-pomodoro
spec:
  type: {{ .Values.pythonPomodoro.service.type }}
  ports:
    - port: 8002
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: python-pomodoro
{{- end }}