# Default values for SRE Todo Helm chart

# Frontend Configuration
frontend:
  enabled: true
  replicas: 1
  image: ghcr.io/eliasschrei/sretodo-frontend
  tag: latest
  pullPolicy: Always
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Java Todo Service
javaTodo:
  enabled: true
  replicas: 1
  image: ghcr.io/eliasschrei/sretodo-service-java-todo
  tag: latest
  pullPolicy: Always
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# .NET Statistik Service
dotnetStatistik:
  enabled: true
  replicas: 1
  image: ghcr.io/eliasschrei/sretodo-service-dotnet-statistik
  tag: latest
  pullPolicy: Always
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Python Pomodoro Service
pythonPomodoro:
  enabled: true
  replicas: 1
  image: ghcr.io/eliasschrei/sretodo-service-python-pomodoro
  tag: latest
  pullPolicy: Always
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# PostgreSQL Database
postgres:
  enabled: true
  replicas: 1
  image: postgres
  tag: "13"
  pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: true
    size: 1Gi
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: sretodo

# Observability Stack
observabilityStack:
  enabled: true

  # OpenTelemetry Collector
  otelCollector:
    image: otel/opentelemetry-collector-contrib
    tag: latest
    pullPolicy: Always

  # Prometheus
  prometheus:
    image: prom/prometheus
    tag: latest
    pullPolicy: Always

  # Tempo
  tempo:
    image: grafana/tempo
    tag: latest
    pullPolicy: Always

  # Loki
  loki:
    image: grafana/loki
    tag: latest
    pullPolicy: Always

  # Grafana
  grafana:
    image: grafana/grafana
    tag: latest
    pullPolicy: Always

# NGINX Gateway
nginxGateway:
  enabled: true
  replicas: 1
  image: nginx
  tag: "alpine"
  pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
