apiVersion: v2
name: sretodo-chart
description: Helm chart für die SREToDo Observability Demo Anwendung

# A chart can be either an 'application' or a 'library' chart.
# Application charts are deployable objects. Library charts provide useful utilities
# or functions for the chart developer. They're included as dependencies of application charts.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0.0"

dependencies:
  # Eigene Services werden direkt getemplated

  # Observability Stack Dependencies
  - name: opentelemetry-collector
    version: "0.117.1"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
    alias: otel-collector # Alias für einfachere Referenz in values.yaml

  - name: prometheus
    version: "27.4.0" # Aktualisiert
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

  - name: loki
    version: "6.29.0" # Aktualisiert gemäss User Info
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled

  - name: tempo
    version: "1.16.0" # Beibehalten, bitte ggf. anpassen
    repository: "https://grafana.github.io/helm-charts"
    condition: tempo.enabled

  - name: grafana
    version: "8.10.1" # Aktualisiert
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled

  # Database Dependency
  - name: postgresql
    version: "16.6.0" # Korrekte aktuelle Version
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
