name: Deploy SRE ToDo Demo to OpenShift

on:
  push:
    branches:
      - main
      - dev
      - feature-250404-start

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Erforderlich für Push zu ghcr.io

    outputs:
      image_tag: ${{ steps.meta-common.outputs.version }} # Git SHA als Tag
      image_repo_frontend: ghcr.io/${{ github.repository_owner }}/sretodo-frontend
      image_repo_java: ghcr.io/${{ github.repository_owner }}/sretodo-java-todo
      image_repo_dotnet: ghcr.io/${{ github.repository_owner }}/sretodo-dotnet-statistik
      image_repo_python: ghcr.io/${{ github.repository_owner }}/sretodo-python-pomodoro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (common)
        id: meta-common
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/sretodo-frontend
            ghcr.io/${{ github.repository_owner }}/sretodo-java-todo
            ghcr.io/${{ github.repository_owner }}/sretodo-dotnet-statistik
            ghcr.io/${{ github.repository_owner }}/sretodo-python-pomodoro
          tags: |
            type=sha,prefix=

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-angular
          push: true
          labels: ${{ steps.meta-common.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Explizite Angabe des ersten Images aus meta-common
          file: ./frontend-angular/Dockerfile
          # Manuelle Angabe des Tags, da build-push-action mehrere Images nicht gut handhabt
          tags: ghcr.io/${{ github.repository_owner }}/sretodo-frontend:${{ steps.meta-common.outputs.version }}

      - name: Build and push Java Todo image
        uses: docker/build-push-action@v5
        with:
          context: ./service-java-todo
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sretodo-java-todo:${{ steps.meta-common.outputs.version }}
          labels: ${{ steps.meta-common.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./service-java-todo/Dockerfile

      - name: Build and push .NET Statistik image
        uses: docker/build-push-action@v5
        with:
          context: ./service-dotnet-statistik
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sretodo-dotnet-statistik:${{ steps.meta-common.outputs.version }}
          labels: ${{ steps.meta-common.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./service-dotnet-statistik/Dockerfile

      - name: Build and push Python Pomodoro image
        uses: docker/build-push-action@v5
        with:
          context: ./service-python-pomodoro
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/sretodo-python-pomodoro:${{ steps.meta-common.outputs.version }}
          labels: ${{ steps.meta-common.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./service-python-pomodoro/Dockerfile

  deploy-to-openshift:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest" # Oder spezifische Version

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          # Optional: Deaktiviert TLS-Verifizierung, falls selbstsignierte Zertifikate verwendet werden
          # insecure_skip_tls_verify: true
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install sretodo-release ./kubernetes \
            --namespace ${{ secrets.OPENSHIFT_NAMESPACE }} \
            --set sretodoFrontend.image.repository=${{ needs.build-and-push.outputs.image_repo_frontend }} \
            --set sretodoFrontend.image.tag=${{ needs.build-and-push.outputs.image_tag }} \
            --set sretodoJavaTodo.image.repository=${{ needs.build-and-push.outputs.image_repo_java }} \
            --set sretodoJavaTodo.image.tag=${{ needs.build-and-push.outputs.image_tag }} \
            --set sretodoDotnetStatistik.image.repository=${{ needs.build-and-push.outputs.image_repo_dotnet }} \
            --set sretodoDotnetStatistik.image.tag=${{ needs.build-and-push.outputs.image_tag }} \
            --set sretodoPythonPomodoro.image.repository=${{ needs.build-and-push.outputs.image_repo_python }} \
            --set sretodoPythonPomodoro.image.tag=${{ needs.build-and-push.outputs.image_tag }} \
            --set sretodoPostgres.enabled=true \
            --set sretodoObservability.enabled=true \
            --set sretodoNginxGateway.enabled=true
            # Fügen Sie hier weitere --set Anweisungen hinzu, falls nötig
